### ISSUE TITLE
RunEngine RuntimeError when following 02 - Hello Bluesky

### ISSUE THREAD

**Issue by robmarkcole** [NSLS-II/bluesky#1080]
Installed bluesky and dependencies locally, working (locally) through the `02 - Hello Bluesky` example notebook from https://try.nsls2.bnl.gov.  On executing the `count` example I receive the following error, and the kernel dies.

```
$ RE(count([noisy_det]))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-19b34aa28bb2> in <module>()
----> 1 RE(count([noisy_det]))

c:\users\rcole\python\bluesky-master\bluesky\run_engine.py in __call__(self, *args, **metadata_kw)
    731             self._task = self.loop.create_task(self._run())
    732             try:
--> 733                 self.loop.run_forever()
    734             finally:
    735                 if self._task.done():

C:\ProgramData\Anaconda3\lib\asyncio\base_events.py in run_forever(self)
    406         self._check_closed()
    407         if self.is_running():
--> 408             raise RuntimeError('This event loop is already running')
    409         if events._get_running_loop() is not None:
    410             raise RuntimeError(

RuntimeError: This event loop is already running

Transient Scan ID: 2     Time: 2018/08/08 13:47:36
Persistent Unique Scan ID: 'e91ccebb-9d60-40a6-8fe1-9fbba8fb31c9'
New stream: 'primary'
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 13:47:36.5 |
+-----------+------------+
generator count ['e91ccebb'] (scan num: 2)
```

## Your Environment
'3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]'
Win 7

**Comment by prjemian** [comment]
Had the same problem recently using jupyter-notebook.  Dan gave me the
solution.  This is the fix until Bluesky is ready for tornado v5.

conda install tornado=4

And you need to "pin" your installation to tornado<5.

**Comment by robmarkcole** [comment]
I believe tornado v5 ships with the Anaconda distro. I appear to have both 4.5 and 5 on my system:
```
tornado                   5.0.2                     <pip>
tornado                   4.5.2            py36h57f6048_0
```
Unfortunately I'm behind a firewall which makes using the package managers a real hassle

**Comment by tacaswell** [comment]
try `pip uninstall tornado` and the `conda install tornado=4 --offline` which will hopefully remove the pip version of tornado and then re-install tornado from a cached version of the conda package.

**Comment by robmarkcole** [comment]
Performed those actions, now have:
```

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>jupyter
 notebook
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook.EXE\__main__.py", line
 5, in <module>

  File "c:\programdata\anaconda3\lib\site-packages\notebook\__init__.py", line 2
5, in <module>
    from .nbextensions import install_nbextension
  File "c:\programdata\anaconda3\lib\site-packages\notebook\nbextensions.py", li
ne 610, in <module>
    from .extensions import (
  File "c:\programdata\anaconda3\lib\site-packages\notebook\extensions.py", line
 8, in <module>
    from tornado.log import LogFormatter
ModuleNotFoundError: No module named 'tornado'

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>conda i
nstall tornado=4 --offline
Fetching package metadata ...............
Solving package specifications: .
Warning: >10 possible package resolutions (only showing differing packages):
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::libiconv-1.14-vc14_4,
conda-forge::libxml2-2.9.4-vc14_4, conda-forge::vc-14-0
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::libxml2-2.9.4-vc14_4,
conda-forge::vc-14-0, defaults::libiconv-1.15-vc14h29686d3_5
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::libiconv-1.14-vc14_4,
conda-forge::vc-14-0, defaults::libxml2-2.9.4-vc14h8fd0f11_5
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::vc-14-0, defaults::lib
iconv-1.15-vc14h29686d3_5, defaults::libxml2-2.9.4-vc14h8fd0f11_5
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::libiconv-1.14-vc14_4,
defaults::libxml2-2.9.4-vc14h8fd0f11_5, defaults::vc-14-h2379b0c_1
  - conda-forge::certifi-2017.7.27.1-py36_0, defaults::libiconv-1.15-vc14h29686d
3_5, defaults::libxml2-2.9.4-vc14h8fd0f11_5, defaults::vc-14-h2379b0c_1
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::libiconv-1.14-vc14_4,
conda-forge::libxml2-2.9.4-vc14_4, defaults::vc-14-h2379b0c_1
  - conda-forge::certifi-2017.7.27.1-py36_0, conda-forge::libxml2-2.9.4-vc14_4,
defaults::libiconv-1.15-vc14h29686d3_5, defaults::vc-14-h2379b0c_1
  - conda-forge::libiconv-1.14-vc14_4, conda-forge::libxml2-2.9.4-vc14_4, defaul
ts::certifi-2017.7.27.1-py36h043bc9e_0, defaults::vc-14-h2379b0c_1
  - conda-forge::libiconv-1.14-vc14_4, conda-forge::libxml2-2.9.4-vc14_4, conda-
forge::vc-14-0, defaults::certifi-2017.7.27.1-py36h043bc9e_0
  ... and others

Package plan for installation in environment C:\ProgramData\Anaconda3:

The following packages will be REMOVED:

    anaconda: 5.0.0-py36hea9b2fc_0
    certifi:  2017.7.27.1-py36h043bc9e_0
    h5py:     2.7.1-py36_1               conda-forge
    hdf5:     1.8.18-vc14_1              conda-forge [vc14]
    libiconv: 1.15-vc14h29686d3_5                    [vc14]
    libpng:   1.6.28-vc14_1              conda-forge [vc14]
    libxml2:  2.9.4-vc14h8fd0f11_5                   [vc14]
    pytables: 3.4.2-np111py36_1          conda-forge
    sqlite:   3.13.0-vc14_0              conda-forge [vc14]
    vc:       14-h2379b0c_1

Proceed ([y]/n)? y


(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>jupyter
 notebook
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook.EXE\__main__.py", line
 5, in <module>

  File "c:\programdata\anaconda3\lib\site-packages\notebook\__init__.py", line 2
5, in <module>
    from .nbextensions import install_nbextension
  File "c:\programdata\anaconda3\lib\site-packages\notebook\nbextensions.py", li
ne 610, in <module>
    from .extensions import (
  File "c:\programdata\anaconda3\lib\site-packages\notebook\extensions.py", line
 8, in <module>
    from tornado.log import LogFormatter
ModuleNotFoundError: No module named 'tornado'

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>conda i
nstall tornado=4 --offline
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 64
0, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 114,
 in _main
    imported = importlib.import_module(module)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import
_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", li
ne 10, in <module>
    from .install import install
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 2
1, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 8,
 in <module>
    from .package_cache import PackageCache
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\package_cache.py",
 line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\path_actions.py",
line 33, in <module>
    from ..gateways.download import download
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\download.py",
line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, S
SLError
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py", line 9
7, in <module>
    from . import utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\utils.py", line 24,
in <module>
    from . import certs
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\certs.py", line 15,
in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 182,
 in main
    return conda_exception_handler(_main, *args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 64
4, in conda_exception_handler
    return handle_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 63
4, in handle_exception
    print_unexpected_error_message(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 59
6, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_info.py", line
 162, in get_info_dict
    from ..connection import user_agent
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\connection.py", line 12
, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py", line 9
7, in <module>
    from . import utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\utils.py", line 24,
in <module>
    from . import certs
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\certs.py", line 15,
in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>conda i
nstall certifi --offline
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 64
0, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 114,
 in _main
    imported = importlib.import_module(module)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import
_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", li
ne 10, in <module>
    from .install import install
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 2
1, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 8,
 in <module>
    from .package_cache import PackageCache
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\package_cache.py",
 line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\path_actions.py",
line 33, in <module>
    from ..gateways.download import download
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\download.py",
line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, S
SLError
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py", line 9
7, in <module>
    from . import utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\utils.py", line 24,
in <module>
    from . import certs
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\certs.py", line 15,
in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 182,
 in main
    return conda_exception_handler(_main, *args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 64
4, in conda_exception_handler
    return handle_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 63
4, in handle_exception
    print_unexpected_error_message(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 59
6, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_info.py", line
 162, in get_info_dict
    from ..connection import user_agent
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\connection.py", line 12
, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\__init__.py", line 9
7, in <module>
    from . import utils
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\utils.py", line 24,
in <module>
    from . import certs
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\certs.py", line 15,
in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>conda i
nstall tornado=4 --offline
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\ProgramData\Anaconda3:
#
tornado                   4.5.2            py36h57f6048_0

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>jupyter
 notebook
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook.EXE\__main__.py", line
 5, in <module>

  File "c:\programdata\anaconda3\lib\site-packages\notebook\__init__.py", line 2
5, in <module>
    from .nbextensions import install_nbextension
  File "c:\programdata\anaconda3\lib\site-packages\notebook\nbextensions.py", li
ne 610, in <module>
    from .extensions import (
  File "c:\programdata\anaconda3\lib\site-packages\notebook\extensions.py", line
 8, in <module>
    from tornado.log import LogFormatter
ModuleNotFoundError: No module named 'tornado'

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>conda i
nstall tornado=4 --offline
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\ProgramData\Anaconda3:
#
tornado                   4.5.2            py36h57f6048_0
```
but cannot run jupyter anymore :-/
```
(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\activate.d>jupyter
notebook
Traceback (most recent call last):
 File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

   "__main__", mod_spec)
 File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook.EXE\__main__.py", line
5, in <module>

 File "c:\programdata\anaconda3\lib\site-packages\notebook\__init__.py", line 2
5, in <module>
   from .nbextensions import install_nbextension
 File "c:\programdata\anaconda3\lib\site-packages\notebook\nbextensions.py", li
ne 610, in <module>
   from .extensions import (
 File "c:\programdata\anaconda3\lib\site-packages\notebook\extensions.py", line
8, in <module>
   from tornado.log import LogFormatter
ModuleNotFoundError: No module named 'tornado'
```

**Comment by tacaswell** [comment]
do a conda remove and then install.  The issues here is conflicting package managers (conda didn't actually do anything because it thought it was already installed, but pip uninstall hand removed the files so it failed to import).

**Comment by robmarkcole** [comment]
OK I ran into this again on my mac, can downgrade tornado to 4 but then jupyter notebooks don't function

**Comment by ronpandolfi** [comment]
I'm having the same issue on Arch, py3.7. Bluesky RE event loop errors with tornado 5.1.1; Jupyter can't start the kernel with tornado 4.1. Here is the notebook error:
```

[I 10:02:29.505 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 467, in initialize
    self.init_sockets()
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 260, in init_sockets
    self.init_iopub(context)
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 268, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/tornado/util.py", line 209, in __new__
    instance.initialize(**args)
  File "/home/rp/PycharmProjects/ophyd/venv/lib/python3.7/site-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
[W 10:02:32.511 NotebookApp] KernelRestarter: restart failed
[W 10:02:32.512 NotebookApp] Kernel 2c322fe3-5a6d-4562-b4bd-a13d23de2aa3 died, removing from map.
```

**Comment by mrakitin** [comment]
@ronpandolfi, does it work with tornado 4.5.2?

**Comment by ronpandolfi** [comment]
Yes it does. Thanks! Citing relevant follow up issue: https://github.com/NSLS-II/bluesky/issues/1062
